import { PlayerStatIds } from './enums/ids/player-stat-ids'

export const statToDescription: Record<PlayerStatIds, (amount: number) => string> = {
  [PlayerStatIds.attackPower]: (amount) => `Increases attack power by ${amount}`,
  [PlayerStatIds.attackSpeed]: (amount) => `Increases attack speed by ${amount}`,
  [PlayerStatIds.arrowRecoveryChance]: (amount) => `${amount}`,
  [PlayerStatIds.cooldownReduction]: (amount) => `Reduces spell cooldown by ${amount} seconds`,
  [PlayerStatIds.critChance]: (amount) => `Increases critical hit chance by ${amount}%`,
  [PlayerStatIds.critMulti]: (amount) => `Increases critical hit multiplier by ${amount * 100}%`,
  [PlayerStatIds.currentManaRegenTimer]: (amount) => ` ${amount}`,
  [PlayerStatIds.currentShopRefreshCooldown]: (amount) => ` ${amount}`,
  [PlayerStatIds.experience]: (amount) => `Increases experience by ${amount}`,
  [PlayerStatIds.extraAirDamage]: (amount) => `Increases air damage by ${amount}`,
  [PlayerStatIds.extraEarthDamage]: (amount) => `Increases earth damage by ${amount}`,
  [PlayerStatIds.extraFireDamage]: (amount) => `Increases fire damage by ${amount}`,
  [PlayerStatIds.extraLightDamage]: (amount) => `Increases light damage by ${amount}`,
  [PlayerStatIds.extraDarkDamage]: (amount) => `Increases dark damage by ${amount}`,
  [PlayerStatIds.extraPhysicalDamage]: (amount) => `Increases physical damage by ${amount}`,
  [PlayerStatIds.extraWaterDamage]: (amount) => `Increases water damage by ${amount}`,
  [PlayerStatIds.goldCoins]: (amount) => `Increases gold coins by ${amount}`,
  [PlayerStatIds.goldCoinsMultiplier]: (amount) => `Increases gold multiplier by ${amount * 100}%`,
  [PlayerStatIds.increasedSpellDuration]: (amount) => `Increases spell duration by ${amount} seconds`,
  [PlayerStatIds.level]: (amount) => `Increases level by ${amount}`,
  [PlayerStatIds.magicDamage]: (amount) => `Increases magic damage by ${amount}`,
  [PlayerStatIds.mana]: (amount) => `Increases mana by ${amount}`,
  [PlayerStatIds.manaRegenRate]: (amount) => `Increases mana regeneration rate by ${amount}`,
  [PlayerStatIds.maxMana]: (amount) => `Increases max mana by ${amount}`,
  [PlayerStatIds.shopRefreshCooldown]: (amount) => ` ${amount}`,
  [PlayerStatIds.unspentSkillPoints]: (amount) => `Gives ${amount} skill points`,
  [PlayerStatIds.xpMultiplier]: (amount) => `Increases experience multiplier by ${amount * 100}%`,
}
